apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2020-02-14T12:21:56Z"
  name: otp-travelsearch-qa-cronjob-otp2
  namespace: default
  resourceVersion: "391062689"
  selfLink: /apis/batch/v1beta1/namespaces/default/cronjobs/otp-travelsearch-qa-cronjob-otp2
  uid: 976ec8a2-4f24-11ea-8b02-42010a8400d2
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: otp-travelsearch-qa-cronjob-otp2
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: TZ
              value: Europe/Oslo
            - name: BUCKET_NAME
              value: otpreport-test.entur.org
            - name: DESTINATION_BLOB_NAME
              value: otp-travelsearch-qa-otp2/reports
            - name: GRAPHQL_ENDPOINT
              value: https://api.dev.entur.io/journey-planner/v3/graphql
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/marduk/marduk-blobstore-credentials.json
            - name: ENDPOINTS_FILE
              value: endpoints.csv
            - name: STOP_TIMES_FILE
              value: stop_times.csv
            - name: PROMETHEUS_PUSH_GATEWAY
              value: http://prometheus-pushgateway.metrics/
            image: eu.gcr.io/entur-system-1287/otp-travelsearch-qa
            imagePullPolicy: Always
            name: otp-travelsearch-qa
            resources:
              limits:
                cpu: 900m
                memory: 550Mi
              requests:
                cpu: 100m
                memory: 400Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/marduk/
              name: marduk-key
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: rutebanken-registry-key
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: marduk-key
            secret:
              defaultMode: 420
              secretName: marduk-carbon-storage-key
  schedule: '*/20 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
status: {}
