version: 2.1
orbs:
  docker: circleci/docker@0.5.20
workflows:
  version: 2.1
  release:
    jobs:
      - docker/publish:
           name: push-release
           registry: eu.gcr.io/entur-system-1287
           image: otp-travelsearch-qa
           tag: '${CIRCLE_SHA1},latest'
           deploy: true
           context: dev
           filters:
             branches:
               only: master
