{{- $dot := . }}
{{- range .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $dot | indent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: {{ $.Values.image.identifier }}
            imagePullPolicy: {{ $.Values.image.imagePullPolicy }}
            env:
            - name: TZ
              value: Europe/Oslo
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/otp-travelsearch-qa/credentials.json
            - name: ENDPOINTS_FILE
              value: endpoints.csv
            - name: STOP_TIMES_FILE
              value: stop_times.csv
            - name: PROMETHEUS_PUSH_GATEWAY
              value: http://prometheus-thanos-pushgateway.metrics/
            - name: BUCKET_NAME
              value: {{ .bucketName}}
            - name: DESTINATION_BLOB_NAME
              value: {{ .destinationBlobName }}
            - name: GRAPHQL_ENDPOINT
              value: {{ .graphqlEndpoint }}
            resources:
              limits:
                cpu: 900m
                memory: 550Mi
              requests:
                cpu: 100m
                memory: 400Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - name: {{ $.Values.secretMount.name }}
                mountPath: {{ $.Values.secretMount.mountPath }}
                subPath: {{ $.Values.secretMount.subPath }}
                readOnly: {{ $.Values.secretMount.readOnly }}
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: {{ $.Values.secretMount.name }}
              secret:
                secretName: {{ $.Values.secretMount.secretName }}
  schedule: '*/20 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
{{- end }}
