---
- set_fact: build_home="/usr/src/jenkinsbuild/workspace/otp-travelsearch-qa"
- set_fact: build_log_directory="/usr/src/log"
- set_fact: logfile="{{build_log_directory}}/otp-travelsearch-qa.log"

- name: Make log directory structure
  file: path={{build_log_directory}} state=directory mode=0755 group=users

- name: Make otp-travelsearch-qa target directory structure
  file: path={{otp_travelsearch_qa_root}}/ state=directory mode=0755 group=users

- name: Copy the otp-travelsearch-qa sources to staging directory
  command: rsync -ar --delete {{ build_home }}/ {{otp_travelsearch_qa_root}}/source

- name: Copy the run script to staging directory
  copy: src=run.sh dest={{otp_travelsearch_qa_root}}/source

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{otp_travelsearch_qa_root}}/Dockerfile mode=0755

- name: Build the otp-travelsearch-qa docker image
  shell: docker build --tag={{ otp_travelsearch_qa_docker_image|quote }} --force-rm=true {{otp_travelsearch_qa_root}} > {{logfile}} 2>&1
  register: image

- name: Push otp-travelsearch-qa docker image if built
  when: image.changed
  shell: docker push {{ otp_travelsearch_qa_docker_image|quote }}
